const content = {
  en: {
    before: {
      icon: '📅',
      heading: 'Switch to Annual Billing',
      subtext: 'Save 20% compared to monthly billing',
      monthlyLabel: 'Monthly',
      monthlyAmount: '$15/mo',
      vs: 'vs',
      annualLabel: 'Annual',
      annualAmount: '$12/mo',
      savings: 'Save $36/yr',
      cta: 'Switch to Annual',
      note: 'No contracts · Cancel anytime',
    },
    after: {
      urgencyPrefix: 'Limited offer — expires in',
      countdown: '2:47:13',
      icon: '🎁',
      heading: 'Get Your First Month FREE',
      subtext: 'Upgrade today and your first month is on us',
      freeTag: 'FREE',
      freeDescBold: '$15 value',
      freeDescEnd: ' — yours immediately when you upgrade',
      cta: 'Claim Free Month Now',
      note: 'Then $15/mo · Cancel anytime',
    },
  },
  ru: {
    before: {
      icon: '📅',
      heading: 'Перейти на годовую оплату',
      subtext: 'Экономия 20% по сравнению с помесячной',
      monthlyLabel: 'Помесячно',
      monthlyAmount: '$15/мес',
      vs: 'vs',
      annualLabel: 'Ежегодно',
      annualAmount: '$12/мес',
      savings: 'Экономия $36/год',
      cta: 'Перейти на год',
      note: 'Без контракта · Отмена в любое время',
    },
    after: {
      urgencyPrefix: 'Ограниченное предложение — истекает через',
      countdown: '2:47:13',
      icon: '🎁',
      heading: 'Получите первый месяц БЕСПЛАТНО',
      subtext: 'Подключите сегодня — первый месяц за наш счёт',
      freeTag: 'FREE',
      freeDescBold: 'Ценность $15',
      freeDescEnd: ' — достаётся сразу при подключении',
      cta: 'Получить бесплатный месяц',
      note: 'Далее $15/мес · Отмена в любое время',
    },
  },
  hy: {
    before: {
      icon: '📅',
      heading: 'Անցնել տարեկան վճարման',
      subtext: 'Խնայեք 20%՝ ամսական վճարման համեմատ',
      monthlyLabel: 'Ամսական',
      monthlyAmount: '$15/ամս',
      vs: 'vs',
      annualLabel: 'Տարեկան',
      annualAmount: '$12/ամս',
      savings: 'Խնայեք $36/տարի',
      cta: 'Անցնել տարեկանի',
      note: 'Առանց պայմանագրի · Չեղարկեք ցանկացած պահի',
    },
    after: {
      urgencyPrefix: 'Սահմանափակ առաջարկ — ավարտվում է՝',
      countdown: '2:47:13',
      icon: '🎁',
      heading: 'Ստացեք ձեր առաջին ամիսն ԱՆՎՃԱՐ',
      subtext: 'Բարելավեք այսօր, և առաջին ամիսը մեր հաշվին է',
      freeTag: 'ԱՆՎՃԱՐ',
      freeDescBold: '$15 արժողությամբ',
      freeDescEnd: ' — անմիջապես ձերն է բարելավման ժամանակ',
      cta: 'Ստանալ անվճար ամիսը հիմա',
      note: 'Այնուհետև $15/ամս · Չեղարկեք ցանկացած պահի',
    },
  },
};

export default content;
