const content = {
  en: {
    before: {
      trialBadge: 'Trial ends in 3 days',
      heading: 'Upgrade to Pro',
      subtext: 'Everything you need to grow your business',
      gains: [
        'Unlimited project creation',
        'Advanced reporting dashboard',
        'Team collaboration tools',
        'Priority customer support',
        'Custom integrations via API',
      ],
      price: '$15',
      priceUnit: '/mo',
      cta: 'Upgrade to Pro',
      skip: 'Maybe later',
    },
    after: {
      trialBadge: '⏰ Trial ends in 3 days',
      heading: 'When your trial ends, you will lose:',
      lossIcon: '✗',
      losses: [
        '12.4 GB of uploaded files',
        '6 saved custom dashboards',
        '3 months of analytics history',
        'All team member access (4 users)',
        '84 saved automation workflows',
      ],
      priceLabel: 'Keep everything for ',
      price: '$15',
      priceUnit: '/mo',
      cta: 'Keep My Data — Upgrade Now',
      skip: 'Discard everything and downgrade',
    },
  },
  ru: {
    before: {
      trialBadge: 'Пробный период заканчивается через 3 дня',
      heading: 'Перейти на Pro',
      subtext: 'Всё, что нужно для роста вашего бизнеса',
      gains: [
        'Неограниченное создание проектов',
        'Расширенная панель отчётов',
        'Инструменты командной работы',
        'Приоритетная поддержка клиентов',
        'Свои интеграции через API',
      ],
      price: '$15',
      priceUnit: '/мес',
      cta: 'Перейти на Pro',
      skip: 'Позже',
    },
    after: {
      trialBadge: '⏰ Пробный период заканчивается через 3 дня',
      heading: 'Когда пробный период закончится, вы потеряете:',
      lossIcon: '✗',
      losses: [
        '12,4 ГБ загруженных файлов',
        '6 сохранённых панелей',
        '3 месяца истории аналитики',
        'Доступ всем участникам команды (4 пользователя)',
        '84 сохранённых сценария автоматизации',
      ],
      priceLabel: 'Сохранить всё за ',
      price: '$15',
      priceUnit: '/мес',
      cta: 'Сохранить данные — перейти сейчас',
      skip: 'Удалить всё и перейти на бесплатный',
    },
  },
  hy: {
    before: {
      trialBadge: 'Փորձաշրջանն ավարտվում է 3 օրից',
      heading: 'Բարելավել դեպի Pro',
      subtext: 'Ամեն ինչ, ինչ ձեզ պետք է բիզնեսը զարգացնելու համար',
      gains: [
        'Անսահմանափակ նախագծերի ստեղծում',
        'Խորացված հաշվետվությունների վահանակ',
        'Թիմային համագործակցության գործիքներ',
        'Հաճախորդների առաջնահերթ աջակցություն',
        'Անհատական ինտեգրացիաներ API-ի միջոցով',
      ],
      price: '$15',
      priceUnit: '/ամս',
      cta: 'Բարելավել դեպի Pro',
      skip: 'Գուցե ավելի ուշ',
    },
    after: {
      trialBadge: '⏰ Փորձաշրջանն ավարտվում է 3 օրից',
      heading: 'Երբ փորձաշրջանն ավարտվի, դուք կկորցնեք՝',
      lossIcon: '✗',
      losses: [
        '12.4 ԳԲ վերբեռնված ֆայլ',
        '6 պահպանված անհատական վահանակ',
        '3 ամիս վերլուծության պատմություն',
        'Բոլոր թիմակիցների մուտքը (4 օգտատեր)',
        '84 պահպանված ավտոմատացման հոսք',
      ],
      priceLabel: 'Պահել ամեն ինչ ',
      price: '$15',
      priceUnit: '/ամս',
      cta: 'Պահել իմ տվյալները — բարելավել հիմա',
      skip: 'Հրաժարվել ամեն ինչից և իջեցնել փաթեթը',
    },
  },
};

export default content;
