const content = {
  en: {
    before: {
      title: 'Annual Pricing',
      plans: [
        {
          name: 'Starter',
          price: '$120',
          unit: '/year',
          features: ['1 user', '5 GB storage'],
          cta: 'Get Starter',
          featured: false,
        },
        {
          name: 'Pro',
          price: '$300',
          unit: '/year',
          features: ['5 users', '50 GB storage'],
          cta: 'Get Pro',
          featured: true,
        },
        {
          name: 'Business',
          price: '$600',
          unit: '/year',
          features: ['Unlimited users', '500 GB storage'],
          cta: 'Get Business',
          featured: false,
        },
      ],
    },
    after: {
      title: 'Simple Daily Pricing',
      plans: [
        {
          name: 'Starter',
          price: '$0.33',
          unit: '/day',
          annual: '$120/year',
          features: ['1 user', '5 GB storage'],
          cta: 'Get Starter',
          featured: false,
          coffeeTag: '',
        },
        {
          name: 'Pro',
          price: '$0.82',
          unit: '/day',
          annual: '$300/year',
          features: ['5 users', '50 GB storage'],
          cta: 'Get Pro',
          featured: true,
          coffeeTag: 'Less than a coffee ☕',
        },
        {
          name: 'Business',
          price: '$1.64',
          unit: '/day',
          annual: '$600/year',
          features: ['Unlimited users', '500 GB storage'],
          cta: 'Get Business',
          featured: false,
          coffeeTag: '',
        },
      ],
    },
  },
  ru: {
    before: {
      title: 'Годовая оплата',
      plans: [
        {
          name: 'Стартовый',
          price: '$120',
          unit: '/год',
          features: ['1 пользователь', '5 ГБ хранилища'],
          cta: 'Выбрать Стартовый',
          featured: false,
        },
        {
          name: 'Pro',
          price: '$300',
          unit: '/год',
          features: ['5 пользователей', '50 ГБ хранилища'],
          cta: 'Выбрать Pro',
          featured: true,
        },
        {
          name: 'Бизнес',
          price: '$600',
          unit: '/год',
          features: ['Неограниченно пользователей', '500 ГБ хранилища'],
          cta: 'Выбрать Бизнес',
          featured: false,
        },
      ],
    },
    after: {
      title: 'Простая оплата по дням',
      plans: [
        {
          name: 'Стартовый',
          price: '$0,33',
          unit: '/день',
          annual: '$120/год',
          features: ['1 пользователь', '5 ГБ хранилища'],
          cta: 'Выбрать Стартовый',
          featured: false,
          coffeeTag: '',
        },
        {
          name: 'Pro',
          price: '$0,82',
          unit: '/день',
          annual: '$300/год',
          features: ['5 пользователей', '50 ГБ хранилища'],
          cta: 'Выбрать Pro',
          featured: true,
          coffeeTag: 'Дешевле кофе ☕',
        },
        {
          name: 'Бизнес',
          price: '$1,64',
          unit: '/день',
          annual: '$600/год',
          features: ['Неограниченно пользователей', '500 ГБ хранилища'],
          cta: 'Выбрать Бизнес',
          featured: false,
          coffeeTag: '',
        },
      ],
    },
  },
  hy: {
    before: {
      title: 'Տարեկան գներ',
      plans: [
        {
          name: 'Սթարթեր',
          price: '$120',
          unit: '/տարի',
          features: ['1 օգտատեր', '5 ԳԲ պահոց'],
          cta: 'Ընտրել Սթարթեր',
          featured: false,
        },
        {
          name: 'Pro',
          price: '$300',
          unit: '/տարի',
          features: ['5 օգտատեր', '50 ԳԲ պահոց'],
          cta: 'Ընտրել Pro',
          featured: true,
        },
        {
          name: 'Բիզնես',
          price: '$600',
          unit: '/տարի',
          features: ['Անսահմանափակ օգտատերեր', '500 ԳԲ պահոց'],
          cta: 'Ընտրել Բիզնես',
          featured: false,
        },
      ],
    },
    after: {
      title: 'Պարզ օրական գներ',
      plans: [
        {
          name: 'Սթարթեր',
          price: '$0.33',
          unit: '/օր',
          annual: '$120/տարի',
          features: ['1 օգտատեր', '5 ԳԲ պահոց'],
          cta: 'Ընտրել Սթարթեր',
          featured: false,
          coffeeTag: '',
        },
        {
          name: 'Pro',
          price: '$0.82',
          unit: '/օր',
          annual: '$300/տարի',
          features: ['5 օգտատեր', '50 ԳԲ պահոց'],
          cta: 'Ընտրել Pro',
          featured: true,
          coffeeTag: 'Սուրճից էժան ☕',
        },
        {
          name: 'Բիզնես',
          price: '$1.64',
          unit: '/օր',
          annual: '$600/տարի',
          features: ['Անսահմանափակ օգտատերեր', '500 ԳԲ պահոց'],
          cta: 'Ընտրել Բիզնես',
          featured: false,
          coffeeTag: '',
        },
      ],
    },
  },
};

export default content;
