const content = {
  en: {
    before: {
      title: 'Complete Purchase',
      orderLabel: 'Order #1304',
      orderPrice: '¥8,400',
      shippingLabel: 'Shipping',
      shippingPrice: '¥0',
      totalLabel: 'Total',
      totalPrice: '¥8,400',
      cta: 'Complete Purchase',
      note: 'Standard global checkout experience',
    },
    after: {
      title: 'ご注文の確認',
      orderLabel: '注文番号 #1305',
      orderPrice: '¥8,400',
      shippingLabel: '送料',
      shippingPrice: '¥0 (無料)',
      totalLabel: '合計',
      totalPrice: '¥8,400',
      cta: 'ご購入を確定する',
      note: '※ #4・#13 の注文番号はご縁を考慮してスキップしています',
      trustBadge: '安全なSSL決済 🔒',
    },
  },
  ru: {
    before: {
      title: 'Оформить покупку',
      orderLabel: 'Заказ №1304',
      orderPrice: '¥8 400',
      shippingLabel: 'Доставка',
      shippingPrice: '¥0',
      totalLabel: 'Итого',
      totalPrice: '¥8 400',
      cta: 'Оформить покупку',
      note: 'Стандартный глобальный чекаут',
    },
    after: {
      title: 'ご注文の確認',
      orderLabel: '注文番号 #1305',
      orderPrice: '¥8,400',
      shippingLabel: '送料',
      shippingPrice: '¥0 (無料)',
      totalLabel: '合計',
      totalPrice: '¥8,400',
      cta: 'ご購入を確定する',
      note: '※ #4・#13 の注文番号はご縁を考慮してスキップしています',
      trustBadge: '安全なSSL決済 🔒',
    },
  },
  hy: {
    before: {
      title: 'Ավարտել գնումը',
      orderLabel: 'Պատվեր #1304',
      orderPrice: '¥8,400',
      shippingLabel: 'Առաքում',
      shippingPrice: '¥0',
      totalLabel: 'Ընդհանուր',
      totalPrice: '¥8,400',
      cta: 'Ավարտել գնումը',
      note: 'Ստանդարտ գլոբալ վճարման փորձառություն',
    },
    after: {
      title: 'ご注文の確認',
      orderLabel: '注文番号 #1305',
      orderPrice: '¥8,400',
      shippingLabel: '送料',
      shippingPrice: '¥0 (無料)',
      totalLabel: '合計',
      totalPrice: '¥8,400',
      cta: 'ご購入を確定する',
      note: '※ #4・#13 の注文番号はご縁を考慮してスキップしています',
      trustBadge: '安全なSSL決済 🔒',
    },
  },
};

export default content;
